# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: steam_auth.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'steam_auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10steam_auth.proto\x12\tsts.login\"6\n\x1eGetPasswordRSAPublicKeyRequest\x12\x14\n\x0c\x61\x63\x63ount_name\x18\x01 \x01(\t\"q\n\rDeviceDetails\x12\x1c\n\x14\x64\x65vice_friendly_name\x18\x01 \x01(\t\x12\x15\n\rplatform_type\x18\x02 \x01(\x05\x12\x0f\n\x07os_type\x18\x03 \x01(\x05\x12\x1a\n\x12gaming_device_type\x18\x04 \x01(\r\"\x9f\x02\n%BeginAuthSessionViaCredentialsRequest\x12\x1c\n\x14\x64\x65vice_friendly_name\x18\x01 \x01(\t\x12\x14\n\x0c\x61\x63\x63ount_name\x18\x02 \x01(\t\x12\x1a\n\x12\x65ncrypted_password\x18\x03 \x01(\t\x12\x1c\n\x14\x65ncryption_timestamp\x18\x04 \x01(\x04\x12\x16\n\x0eremember_login\x18\x05 \x01(\x08\x12\x15\n\rplatform_type\x18\x06 \x01(\x05\x12\x13\n\x0bpersistence\x18\x07 \x01(\x05\x12\x12\n\nwebsite_id\x18\x08 \x01(\t\x12\x30\n\x0e\x64\x65vice_details\x18\t \x01(\x0b\x32\x18.sts.login.DeviceDetails\"q\n*UpdateAuthSessionWithSteamGuardCodeRequest\x12\x11\n\tclient_id\x18\x01 \x01(\x04\x12\x0f\n\x07steamid\x18\x02 \x01(\x06\x12\x0c\n\x04\x63ode\x18\x03 \x01(\t\x12\x11\n\tcode_type\x18\x04 \x01(\x05\"E\n\x1cPollAuthSessionStatusRequest\x12\x11\n\tclient_id\x18\x01 \x01(\x04\x12\x12\n\nrequest_id\x18\x02 \x01(\x0c')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'steam_auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETPASSWORDRSAPUBLICKEYREQUEST']._serialized_start=31
  _globals['_GETPASSWORDRSAPUBLICKEYREQUEST']._serialized_end=85
  _globals['_DEVICEDETAILS']._serialized_start=87
  _globals['_DEVICEDETAILS']._serialized_end=200
  _globals['_BEGINAUTHSESSIONVIACREDENTIALSREQUEST']._serialized_start=203
  _globals['_BEGINAUTHSESSIONVIACREDENTIALSREQUEST']._serialized_end=490
  _globals['_UPDATEAUTHSESSIONWITHSTEAMGUARDCODEREQUEST']._serialized_start=492
  _globals['_UPDATEAUTHSESSIONWITHSTEAMGUARDCODEREQUEST']._serialized_end=605
  _globals['_POLLAUTHSESSIONSTATUSREQUEST']._serialized_start=607
  _globals['_POLLAUTHSESSIONSTATUSREQUEST']._serialized_end=676
# @@protoc_insertion_point(module_scope)
